### ISSUE TITLE
Erro no run restore Angular

### ISSUE THREAD

**Issue by souzagustavo** [bdiogoandre/d1-engineering#1]
![image](https://user-images.githubusercontent.com/35812662/63610411-d0877e00-c5af-11e9-9dfb-f0d2ddd4a183.png)

**log**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'restore' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose stack Error: missing script: restore
4 verbose stack     at run (C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd D:\Developer\Testes\d1-engineering\frontend
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "restore"
8 verbose node v10.15.3
9 verbose npm  v6.4.1
10 error missing script: restore
11 verbose exit [ 1, true ]

**Comment by bdiogoandre** [comment]
Tente o comando npm install --save para instalar as dependências do node_modules.

**Comment by souzagustavo** [comment]
@bdiogoandre 
O comando instalou todos os pacotes corretamente. Rodei **npm start** e do App subiu.
